### PR TITLE
Setup Travis

### PR DESCRIPTION
**Pull request by thebeanogamer**
NOT DONE DO NOT MERGE

### CODE REVIEW

**Comment by thebeanogamer** [comment]
@NateKomodo Can you provide any insight here? 
image

**Comment by NateKomodo** [comment]
You dont appear to have UIAutomation (Which is used for pulling the chrome bar) in the GAC @thebeanogamer

**Comment by NateKomodo** [comment]
Get the DLLs for UIAutomation and UIAutomationTypes and you should be good

**Comment by NateKomodo** [comment]
UIAutomationClient as well it would seem

**Comment by thebeanogamer** [comment]
This is being closed as I work to implement Azure Devops instead.

**Pull request closed without merging**
